apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: breakfast-menu
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/sdctf-307600/breakfast-menu-challenge:578cc84c424f649b6823d4674ef9f213dca0a8e1a14bfbb7e9e2bec8ae90e570
