apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: negotiate-warden
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/sdctf-307600/negotiate-warden-challenge:71ef22b3574eb95b3f362c3bd327af053915b4ee5bb4c73c0b94901cdaa6a789
