apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: logs
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
      - protocol: "TCP"
        port: 1338
        targetPort: 1338
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: eu.gcr.io/sdctf-307600/logs-challenge:bc462d9b14ec57fc7f77e03674b01dde3f3fffc79070c18e11780ad813904d85
