apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: symcaljs
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/sdctf-307600/symcaljs-challenge:b5fce789e03a44cb18a8cd36bd114961f2747387758a759bbacd0681d1a976e2
