[package]
name = "bishop-duel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
text_io = "0.1.10"
rand = "0.8.5"