apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  #change to chal name
  name: secure-horoscope
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/sdctf-307600/secure-horoscope-challenge:3ec62ed702d6901495fac027ce1fb298af3f9d17fd95022df7ed5b0339c82dab
